advanced: Sync ownership
syncthing/docs pull request #759
Opened 2022-07-05 11:39 UTC by calmh

2022-07-09 21:50 UTC, acolomb requested changes
Small typos.  Excited to see how the rest of it turns out.  Unfortunately I can't help with Windows stuff much, as I tend to avoid that OS when possible.

2022-07-09 21:50 UTC, acolomb commented on advanced/folder-sync-ownership.rst
> +Syncthing records both the numberical UID and GID for a file and the
```suggestion
Syncthing records both the numerical UID and GID for a file and the
```

2022-07-09 21:50 UTC, acolomb commented on advanced/folder-sync-ownership.rst
> +- As a normal user, with extra capabilities granted the executable.
```suggestion
- As a normal user, with extra capabilities granted to the executable.
```

2022-07-26 06:45 UTC, acolomb commented
The "Elevated Permissions" headline is duplicated, please remove at the end.

Would you mind integrating the option in `users/config.rst` as well, in the examples and as an `.. option::` definition?  That's needed to make the GUI links work.  Just linking to the new page should be sufficient.

2022-07-26 07:38 UTC, calmh commented
The duplication was intended, in that it is different in POSIX (which I'll rename to Unix) and Windows... But since there's currently nothing I can say about how this works in Windows I'll just skip that part.

2022-07-28 17:44 UTC, merged