Update usage.rst
syncthing/docs pull request #776
Opened 2022-12-02 21:17 UTC by leunga1000

2022-12-02 22:46 UTC, acolomb requested changes
This is factually wrong. When Syncthing is stopped, as recommended, no `syncthing cli` command can really work. And it requires access to the API key, which the previously recommended command doesn't (that's fine however, assuming both variants need direct access to the config file).

2022-12-05 20:05 UTC, acolomb requested changes
I'm not fond of dropping the previous approach completely.  Listing the config CLI commands is fine, but it assumes that Syncthing is still running and the API can be accessed.  Better add this variant as an alternative, but keep the existing methods as they were.

Please make sure to blend in with the surrounding text regarding both style and formatting (esp. line wrapping).

2022-12-05 20:05 UTC, acolomb commented on users/faq-parts/usage.rst
> -2. ``syncthing generate --gui-password=myNewPassword --gui-user=newUserName``
The "step 2" referenced below is now something different.  In fact, the whole following paragraph doesn't make much sense if you only document the CLI commands.

2022-12-05 20:13 UTC, leunga1000 commented
> I'm not fond of dropping the previous approach completely. Listing the config CLI commands is fine, but it assumes that Syncthing is still running and the API can be accessed. Better add this variant as an alternative, but keep the existing methods as they were.
> 
> Please make sure to blend in with the surrounding text regarding both style and formatting (esp. line wrapping).

I think there's something fundamentally I'm missing here, `syncthing generate` returns an error for me.

2022-12-05 21:40 UTC, acolomb commented
> I think there's something fundamentally I'm missing here, `syncthing generate` returns an error for me.

Well what is the error?  The documented procedure usually does work, so if you're just having trouble using it, let's diagnose why.

2022-12-06 11:11 UTC, closed without merging