users: New default config/data locations
syncthing/docs pull request #833
Opened 2023-10-22 21:04 UTC by calmh

See syncthing/syncthing#9180

2023-10-22 21:26 UTC, imsodin approved these changes

2023-10-22 21:31 UTC, acolomb requested changes
Nicely done, but some corrections necessary.

2023-10-22 21:31 UTC, acolomb commented on users/config.rst
> +The config location defaults to ``$XDG_STATE_HOME/syncthing`` or
```suggestion
The location defaults to ``$XDG_STATE_HOME/syncthing`` or
```

I think talking especially about a "config location" here can be confusing after the previous statement.  Please reflow at will if accepting the suggestion. :wink:

2023-10-22 21:31 UTC, acolomb commented on users/config.rst
> +platforms only) for legacy reasons:
We should mention the legacy *config* location as well, i.e. `%XDG_CONFIG_HOME/syncthing` and `$HOME/.config/syncthing`, as they are is still tried.

2023-10-22 21:31 UTC, acolomb commented on users/config.rst
> +:file:`syncthing.log`
`csrftokens.txt` also lands here if I read the code correctly.  Move from the paragraph above please.

2023-10-22 21:31 UTC, acolomb commented on users/faq-parts/troubleshooting.rst
>  activities, which contains a ``JSON`` formatted  sequence of events in the
Nitpick: Double space.  Which is fine after a full-stop (end of sentence), but not within.

```suggestion
activities, which contains a ``JSON`` formatted sequence of events in the
```

2023-10-22 21:33 UTC, acolomb commented
Oh and we should maybe have a `..versionadded::` tag here somewhere, to make it explicit when the defaults changed.

2023-10-23 06:22 UTC, calmh commented
I rewrote stuff to be, in my mind, a bit clearer. A new `versionadded` describes the change. Then we don't need to deal with the change/legacy further down in the doc. I deliberately left out mentioning csrftokens.txt (but missed removing it from the old config section) because it's a tiny implementation wart that should go away (live in the database, if anywhere) -- it's covered by the new "among others" on the database dir. :)

2023-10-23 06:25 UTC, calmh commented
n.b. the `versionchanged` is next+1 since I think this is too dangerous a change to slide into an `rc.2`. We should delay merge accordingly (of the docs change), until after 1.26 release.

2023-11-13 10:25 UTC, merged